// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCIKC5G79Cvc6XLJRNF4Xx7em_3hjlp0',
    appId: '1:792763520034:web:dcef6d6fcd464cff37667b',
    messagingSenderId: '792763520034',
    projectId: 'ausy-mobile',
    authDomain: 'ausy-mobile.firebaseapp.com',
    storageBucket: 'ausy-mobile.firebasestorage.app',
    measurementId: 'G-CLF1X9X31Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBELvqM5q-DYbZ00v37-t6GY3pA_4UdaSA',
    appId: '1:792763520034:android:afa0ace87c5e1d2d37667b',
    messagingSenderId: '792763520034',
    projectId: 'ausy-mobile',
    storageBucket: 'ausy-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-B4a5_Id_W9KczpuBWAhRswndo1e7Tg',
    appId: '1:792763520034:ios:75a5cac51056ee4937667b',
    messagingSenderId: '792763520034',
    projectId: 'ausy-mobile',
    storageBucket: 'ausy-mobile.firebasestorage.app',
    iosBundleId: 'com.ausy.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-B4a5_Id_W9KczpuBWAhRswndo1e7Tg',
    appId: '1:792763520034:ios:9430b9af6e3a3c5d37667b',
    messagingSenderId: '792763520034',
    projectId: 'ausy-mobile',
    storageBucket: 'ausy-mobile.firebasestorage.app',
    iosBundleId: 'com.erpnext.pos.erpnext',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpCIKC5G79Cvc6XLJRNF4Xx7em_3hjlp0',
    appId: '1:792763520034:web:f48509e0155befaa37667b',
    messagingSenderId: '792763520034',
    projectId: 'ausy-mobile',
    authDomain: 'ausy-mobile.firebaseapp.com',
    storageBucket: 'ausy-mobile.firebasestorage.app',
    measurementId: 'G-NQ2RC867B7',
  );
}
